### ISSUE TITLE
Replace SOAP code with WikiPathways REST calls

### ISSUE THREAD

**Issue by egonw** [BiGCAT-UM/wp2lod#2]
Because SOAP is being phased out. Symptom:

    run:
         [java] Exception in thread "main" AxisFault
         [java]  faultCode: {http://xml.apache.org/axis/}HTTP
         [java]  faultSubcode: 
         [java]  faultString: (500)Internal Server Error
         [java]  faultActor: 
         [java]  faultNode: 
         [java]  faultDetail: 
         [java] 	{}:return code:  500
         [java] &lt;html&gt;
         [java] 		&lt;head&gt;
         [java] 		&lt;title&gt;Database error&lt;/title&gt;
         [java] 		&lt;/head&gt;
         [java] 		&lt;body&gt;
         [java] 		&lt;h1&gt;&lt;img src='http://www.wikipathways.org/skins/common/images/earth-   or-pathway_text3_beta.png' style='float:left;margin-right:1em' alt=''&gt;Database error&lt;/h1&gt;
         [java] 		A database query syntax error has occurred.
         [java] This may indicate a bug in the software.
         [java] The last attempted database query was:
         [java] &lt;blockquote&gt;&lt;tt&gt;INSERT  INTO `webservice_log`    (ip,operation,request_timestamp) VALUES ('137.120.17.101','&amp;lt;listOrganisms    xmlns=\&amp;quot;http://www.wso2.org/php/xsd\&amp;quot;/','20150204120808')&lt;/tt&gt;&lt;/blockquote&gt;
         [java] from within function &quot;&lt;tt&gt;Database::insert&lt;/tt&gt;&quot;.
         [java] MySQL returned error &quot;&lt;tt&gt;145: Table './wikipathways/webservice_log' is marked    as crashed and should be repaired (localhost)&lt;/tt&gt;&quot;.&lt;/body&gt;&lt;/html&gt;
         [java] 	{http://xml.apache.org/axis/}HttpErrorCode:500
         [java] 
         [java] (500)Internal Server Error
         [java] 	at org.apache.axis.transport.http.HTTPSender.readFromSocket(HTTPSender.java:744)
         [java] 	at org.apache.axis.transport.http.HTTPSender.invoke(HTTPSender.java:144)
         [java] 	at org.apache.axis.strategies.InvocationStrategy.visit(InvocationStrategy.java:32)
         [java] 	at org.apache.axis.SimpleChain.doVisiting(SimpleChain.java:118)
         [java] 	at org.apache.axis.SimpleChain.invoke(SimpleChain.java:83)
         [java] 	at org.apache.axis.client.AxisClient.invoke(AxisClient.java:165)
         [java] 	at org.apache.axis.client.Call.invokeEngine(Call.java:2784)
         [java] 	at org.apache.axis.client.Call.invoke(Call.java:2767)
         [java] 	at org.apache.axis.client.Call.invoke(Call.java:2443)
         [java] 	at org.apache.axis.client.Call.invoke(Call.java:2366)
         [java] 	at org.apache.axis.client.Call.invoke(Call.java:1812)
         [java] 	at    org.pathvisio.wikipathways.webservice.WikiPathwaysSOAPBindingStub.listOrganisms(Unknown    Source)
         [java] 	at org.pathvisio.wikipathways.WikiPathwaysClient.listOrganisms(Unknown Source)
         [java] 	at WpRDFFunctionLibrary.getOrganismsTaxonomyMapping(WpRDFFunctionLibrary.java:294)
         [java] 	at WP2RDFConversion.main(WP2RDFConversion.java:64)

**Comment by mkutmon** [comment]
SOAP should still be working fine now. I also have issues with the bots, so I will check it out. Before SOAP will phase out, we will clearly notify everyone!
