### ISSUE TITLE
Looking into the 'error' raised for KEGG Compound identifiers

### ISSUE THREAD

**Issue by egonw** [BiGCAT-UM/wp2lod#4]
Resulting in this WPRDF (from WP465):

    rdfs:subClassOf <http://rdf.wikipathways.org/error/C00332> ;
    dc:source "KEGG Compound"^^xsd:string ;

**Comment by kmhettne** [comment]
<http://rdf.wikipathways.org/Pathway/WP2788_r77079/DataNode/c7bb0>
      a       wp:Protein , gpml:DataNode , skos:Concept ;
      rdfs:isDefinedBy gpml:DataNode ;
      rdfs:label "ACER3"@en ;
      rdfs:subClassOf <http://rdf.wikipathways.org/error/Q9NUN7> ;
      dc:source "Uniprot-TrEMBL"^^xsd:string ;
      dcterms:identifier "Q9NUN7"^^xsd:string ;

**Comment by egonw** [comment]
The code is using a Turtle serialized datasources.txt and identifiers are mapped based on the full name (because that's the only thing possible from GPML). But the current BioDataSources.ttl had old names ("Uniprot/TrEMBL" and "Kegg Compound") causing the "error" URIs...

**Comment by egonw** [comment]
I have updated the BioDataSources.ttl
